nt_training/urls.py
from django.urls import path

from . import views

app_name = 'nt_training'
urlpatterns = [

	# Authentication
	#/login
	path('login/', views.NTLoginView.as_view(), name='ntLogin'),
	#/logout
	path('logout/', views.NTLogoutView.as_view(), name='ntLogout'),
	#/user
	path('user/done/', views.NTUserEditDone.as_view(), name='ntUserEditDone'),
	path('user/', views.NTUserEdit.as_view(), name='ntUserEdit'),

	#/
	path('', views.HomeView.as_view(), name='ntHome'),

	# People Views
	#/people
	path('people/', views.PeopleView.as_view(), name='ntPeople'),
	#/people/slug
	path('people/<slug:slug>', views.PersonView.as_view(), name='ntPerson'),
	
	# Training Spec Views
	#/training
	path('training/', views.TrainingView.as_view(), name='ntCategory'),
	#/training/id
	path('training/<int:pk>/', views.TrainingDetailView.as_view(), name='ntTrainingDetail'),

	# Training Session Views
	#/training/session (List view)
	path('training/session/', views.SessionView.as_view(), name='ntSessions'),
	#/training/session/id (Single view)
	path('training/session/<int:pk>/', views.SessionSingleView.as_view(), name='ntSessionSingle'),
	## Login required (handled in views.py)
	#/training/session/new (Create view)
	path('training/session/new/', views.SessionNewView.as_view(), name='ntSessionNew'),
	#/training/session/id/edit (Update view)
	path('training/session/<int:pk>/edit/', views.SessionEditView.as_view(), name='ntSessionEdit'),

	# About Page 
	#/about
	path('about/', views.AboutView.as_view(), name='ntAbout'),

]
handler404 = views.PageNotFoundView.as_view()

training/urls.py
from django.conf import settings
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('nt_training.urls')),
    url(r'^admin/', admin.site.urls),
]
# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns =  [
#         url(r'^__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

nt_training/models.py
import datetime

from django.db import models
from django.db.models.functions import Lower
from django.utils import timezone

# Create your models here.

# NNT Training Models

class Department(models.Model):
	class Meta:
		ordering = ['weight']

	name = models.CharField(
		verbose_name = "Department Name",
		max_length = 50
	)
	person = models.CharField(
		help_text = "Person in charge of the department",
		max_length = 50
	)
	email = models.EmailField(
		help_text = "Email address of the person in charge"
	)
	weight = models.IntegerField(
		unique = True 
	)
	department_icon = models.CharField(
		max_length=25,
		verbose_name = "Icon Code",
		default="fa fa-",
		help_text = 'From <a href="https://fontawesome.com/icons?d=gallery&m=free">Font Awesome 5</a>. Example: <code>fas fa-user</code>.'
	)
	def __str__(self):
		return str(self.name)

class Site_Page(models.Model):
	class Meta:
		verbose_name = "Site Page"
		ordering = ['weight']
	page_title = models.CharField(
		max_length = 25,
	)
	weight = models.IntegerField()
	primary = models.BooleanField(default=False)
	viewName = models.CharField(max_length=25)
	description = models.TextField(
		null=True,
		blank=True,
	)
	iconRef = models.CharField(
		max_length=25,
		verbose_name = "Icon Code",
		help_text = 'From <a href="https://fontawesome.com/icons?d=gallery&m=free">Font Awesome 5</a>. Example: <code>fas fa-user</code>.'
	)
	iconRef.short_description = "Icon Code"
	def __str__(self):
		return self.page_title

class Category(models.Model):
	class Meta:
		ordering = ['weight']
		verbose_name = "Training Category"
		verbose_name_plural = "Training Categories"

	iconRef = models.CharField(
		max_length=25,
		verbose_name = "Icon Code",
		help_text = 'From <a href="https://fontawesome.com/icons?d=gallery&m=free">Font Awesome 5</a>. Example: <code>fas fa-user</code>.'
	)
	iconRef.short_description = "Icon Code"
	iconName = models.CharField(
		max_length=25,
		verbose_name = 'Category Name'
	)
	weight = models.IntegerField()
	department = models.ForeignKey(
		Department,
		on_delete=models.SET_NULL,
		blank=True,
		null=True,
		help_text = "Department this category belongs to. If you're using departments, you <strong>must</strong> set this for the category to appear."
	)
	description = models.TextField(
		null=True,
		blank=True,
	)
	def __str__(self):
		return str(self.weight) + '. ' + self.iconName

class Person(models.Model):
	first_name = models.CharField(max_length=50)
	last_name = models.CharField(max_length=50)
	grad_year = models.IntegerField(null=True,blank=True,)
	committee = models.BooleanField(default=False)
	email = models.EmailField(
		null=True,
		# default=None,
	 	blank=True,
	)
	status = models.CharField(
		max_length = 15,
		choices = (
			('GRAD', 'Graduated'),
			('STU', 'Student'),
			('UNKNOWN', 'Unknown')
		),
		null = False,
		default='UNKNOWN'
	)
	is_trainer = models.BooleanField(
		default=False,
		help_text="Tick if this person trains others."
	)
	slug = models.SlugField(
		max_length=100,
		null = True,
		unique = True,
	)
	slug.short_description = "Name"
	def __str__(self):
		full_name = self.first_name + ' ' + self.last_name
		#full_name = str.title(full_name)
		return full_name

	class Meta:
		ordering = ['last_name', 'first_name']
		

class Training_Spec(models.Model):
	class Meta:
		verbose_name = "Training Specification"
		ordering = ['category', 'trainingId']

	trainingId = models.DecimalField(
		max_digits = 4,
		decimal_places = 2,
		unique = True,
	)
	category = models.ForeignKey(
		Category,
		on_delete=models.DO_NOTHING,
	)
	trainingTitle = models.CharField(
		max_length=50,
		verbose_name = "Training Title"
	) 
	description = models.TextField(default="Provide a useful description")
	safety = models.BooleanField(
		default=False,
		help_text = "Tick if training point has a health and safety element, or requires a period of supervision before signing off."
	)

	def __str__(self):
		humanTitle = str(self.trainingId) + ' - ' +  self.trainingTitle
		return humanTitle

class Training_Session(models.Model):
	class Meta:
		verbose_name = "Training Session"

	trainingId = models.ManyToManyField(Training_Spec)
	trainer = models.ForeignKey(Person, on_delete=models.DO_NOTHING, related_name="trainer")
	trainee = models.ManyToManyField(Person, related_name="trainee")
	date = models.DateField(
		default = datetime.date.today
	)
	def __str__(self):
		trainees = [] 
		for person in self.trainee.all():
			name = str.title(person.first_name) + ' ' + (str.title(person.last_name))
			trainees.append(name)
		string = str.title(self.trainer.first_name + ' ' + self.trainer.last_name) + ' taught ' + ', '.join(map(str,trainees))
		return string

	def get_absolute_url(self):
		return reverse('nt_training:ntSessions', kwargs={'pk': self.pk})

	def get_students(self):
		return self.trainee.all().filter(status='STU')

nt_training/forms.py
#Import
##Global
import datetime
##Django
from django import forms 
from django.urls import reverse
##DB
from .models import Category, Training_Spec, Person, Training_Session

class DateInput(forms.DateInput):
		input_type = 'date'

class SessionForm(forms.ModelForm):
	# Model: Training_Session. All of these fields are within this model. 
	class Meta:
		model = Training_Session
		fields = ['trainer', 'trainee', 'trainingId', 'date']
		labels = {
			'trainingId': 'Training Points',
			'trainee': 'People Trained',
			'trainer': 'Trainer'
		}
		widgets = {
			'date': DateInput(),
			'trainingId': forms.CheckboxSelectMultiple(),
			'trainee': forms.CheckboxSelectMultiple(),
		}

	def __init__(self, *args, **kwargs):
		super(SessionForm, self).__init__(*args, **kwargs)
		self.fields['trainer'].queryset = Person.objects.filter(is_trainer=True)

	def clean(self):
		trainee = self.cleaned_data.get('trainee')
		trainingId = self.cleaned_data.get('trainingId')
		trainer = self.cleaned_data.get('trainer')
		errors = {}
		# Can't submit without a valid trainer or date, so don't need to validate those.
		if trainee is None:
			errors['trainee'] = forms.ValidationError('Please select some trainees.')
		if trainingId is None:
			errors['trainingId'] = forms.ValidationError("You can't have a session without something to learn. Please select some training points.")
		if trainee is not None:
			if trainer in trainee.all(): # But the trainer should not be in the list of trainees.
				errors['trainer'] = forms.ValidationError("The trainer can't train themselves!")

		if errors:
			raise forms.ValidationError(errors)
			return self.cleaned_data
		
		# return self.cleaned_data

nt_training/views.py
# Django includes
from django.contrib import messages, auth
from django.contrib.auth import authenticate, login
from django.contrib.auth import views as auth_views
from django.contrib.auth.signals import user_logged_in, user_logged_out
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator 
from django.db.models.functions import Lower
from django.forms.models import modelformset_factory
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.template import loader
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views import generic
from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView

# DB Includes
from .models import Site_Page, Department, Category, Person, Training_Session, Training_Spec

# Forms
from .forms import SessionForm

# NNT Training Views

class PageNotFoundView(generic.ListView):
	template_name = "nt_training/404.html"

class HomeView(generic.ListView):
	model = Site_Page
	template_name = "nt_training/index.html"
	context_object_name = "page_list"

class AboutView(generic.TemplateView):
	model = Department
	template_name = "nt_training/about.html"
	def get_context_data(self):
		context = {} 
		context['departments'] = Department.objects.all()
		return context 

class PeopleView(generic.ListView):
	template_name = "nt_training/people.html"
	model = Person
	context_object_name = "context"

	def get_context_data(self):
		context = {}
		# Get all the people. Lower required to allow for mixed-case in DB
		context['people'] = Person.objects.all()
		# Get the training categories
		context['cats'] = Category.objects.order_by('weight').only('iconName')
		context['departments'] = Department.objects.all()
		return context

class PersonView(generic.DetailView):
	template_name = "nt_training/people-single.html"
	model = Person

class TrainingView(generic.ListView):
	model = Training_Spec
	template_name = "nt_training/training.html"
	context_object_name = "training"

class TrainingDetailView(generic.DetailView):
	template_name = "nt_training/training-detail.html"
	model = Training_Spec
	context_object_name = "item"

class SessionView(generic.ListView):
	template_name = "nt_training/session.html"
	model = Training_Session
	def get_queryset(self):
		sessions = Training_Session.objects.order_by('-date')
		return sessions 
	paginate_by = 24
	context_object_name = "sessions"

class SessionSingleView(generic.DetailView):
	model = Training_Session
	template_name = "nt_training/session-single.html"

def is_nt_staff(user):
	return user.groups.filter(name='NT Staff').exists()


@method_decorator(login_required, name='dispatch')
@method_decorator(user_passes_test(is_nt_staff), name='dispatch')
class SessionNewView(SuccessMessageMixin, CreateView):
	model = Training_Session
	form_class = SessionForm
	template_name = "nt_training/session-form.html"
	success_message = "Session created successfully."

	def get_success_url(self):
		return reverse_lazy('nt_training:ntSessionSingle', kwargs={'pk': self.object.pk })

@method_decorator(login_required, name='dispatch')
@method_decorator(user_passes_test(is_nt_staff), name='dispatch')
class SessionEditView(SuccessMessageMixin, UpdateView):
	model = Training_Session
	form_class = SessionForm
	template_name = "nt_training/session-form.html"
	success_message = "Session edited successfully."

	def get_success_url(self):
		return reverse_lazy('nt_training:ntSessionSingle', kwargs={'pk': self.object.pk})

# Auth Views

class NTLoginView(auth_views.LoginView):
	template_name = "nt_training/login.html"


class NTLogoutView(auth_views.LogoutView):
	extra_context = {'logged_out': True }
	template_name = "nt_training/index.html"

# Already have login_required inherently
class NTUserEdit(auth_views.PasswordChangeView):
	template_name = "nt_training/user-edit.html"
	def get_success_url(self):
		return reverse_lazy('nt_training:ntUserEditDone')

class NTUserEditDone(auth_views.PasswordChangeDoneView):
	template_name = "nt_training/user-edit-done.html"

# Flash Messages

def logged_in_message(sender, user, request, **kwargs):
    # Add a welcome message when the user logs in
    messages.success(request, "Login successful!")
def logged_out_message(sender, user, request, **kwargs):
    # Add a welcome message when the user logs in
    messages.info(request, "You have logged out.")

user_logged_in.connect(logged_in_message)
user_logged_out.connect(logged_out_message)

nt_training/templates/nt_training/base.html
{% load static %}
{% load nt_navbar %}

<!DOCTYPE html>
<html>
	<!-- <head> section of pages -->
	<head> 
	  <meta charset="utf-8">
	  <meta http-equiv="X-UA-Compatible" content="IE=edge">
	  <meta name="viewport" content="width=device-width, initial-scale=1">

		<title>{% block title %}Title{% endblock %} | NNT Training</title>

  	<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,400italic,600|Montserrat:400,500,600,700' rel='stylesheet' type='text/css'>

		<!-- Popper.js (for Bootstrap 4) -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>

		<!-- JQuery -->
		<script
		  src="https://code.jquery.com/jquery-3.2.1.min.js"
		  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
		  crossorigin="anonymous"></script>

		<!-- Bootstrap JS --> 
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
		
		<!-- FontAwesome --> 
		<script src="https://kit.fontawesome.com/de8717ca80.js"></script>

		<!-- Training CSS -->
		<link rel="stylesheet" href="{% static 'nt_training/css/screen.css' %}">

	</head>
	<body>
		<!-- Nav bar -->
		<nav class="navbar navbar-expand-md navbar-dark navbar-static-top mb-4">
		  <div class="container">
		  	<div class="col col-md-4">
		      <a class="navbar-brand" href="{% url 'nt_training:ntHome' %}" style="height:auto">
		        <img src="https://newtheatre.org.uk/static/images/logos/nt_logo-web.png" />
		      </a>
				  <button class="navbar-toggler float-right" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
				    <span class="navbar-toggler-icon"></span>
				  </button>
		    </div>
		    <div id="navbar" class="collapse navbar-collapse justify-content-end">
		      <!-- Login buttons and dropdown --> 
		      <ul class="navbar-nav order-md-2 ml-0 h6">
		      	{% if user.is_authenticated %}
		      	<div class="dropdown">
		      		<li class="nav-item">
		      			<a href="#" class="dropdown-toggle nav-item nav-link" data-toggle="dropdown">Hi, {% if user.first_name %}{{ user.first_name|title }}{% else %}{{ user|title }}{% endif %}. <i class="caret"></i></a>
		      			<ul class="dropdown-menu">
		      				{% if user.is_staff %}
		      					<li><a href="/admin" class="dropdown-item">Admin</a></li>
		      				{% endif %}
		      				<li><a href="{% url 'nt_training:ntUserEdit' %}" class="dropdown-item">Change password</a></li>
		      				<li><a href="{% url 'nt_training:ntLogout' %}" class="dropdown-item">Logout</a></li>
		      			</ul>
		      		</li>
		      	</div>
		      	{% else %}
		      		<li class="nav-item"><a href="{% url 'nt_training:ntLogin' %}?next={{ request.path }}" class="nav-link">Login</a></li>
		      	{% endif %}
		      </ul>
		      <!-- Actual navbar buttons -->
		      <ul class="navbar-nav order-md-1 mr-md-auto pl-md-4 h6">
		      	{% nav_items %}
		      </ul>
		    </div><!--/.nav-collapse -->
		  </div>
		</nav>	
		<!-- End nav bar -->

		<div class="container">
			{% for message in messages %}
				<div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %} alert-dismissable">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					{% if message.tags == 'alert' %}<i class="fa fa-fw fa-exclamation-circle"></i>&nbsp;
					{% else %}<i class="fa fa-fw fa-info-circle"></i>&nbsp;
					{% endif %}
					{{ message }}
				</div>
			{% endfor %}
			<br />
			{% block content %}
				<p>No content defined.</p>
			{% endblock %}
		</div>
		<div class="modal" tabindex="-1" role="dialog" id="modalwizard">
		</div>
		<!-- Footer -->
		<div class="container">
			<hr>
			<div class="row">
				<div class="col">
					<p class="text-center text-muted"><small>&copy; 2019 <a href="http://newtheatre.org.uk" class="nocolor clickme">Nottingham New Theatre</a></small></p>
				</div>
			</div>
		</div>
		<!-- End footer -->

		<!-- Javascript -->

			<!-- Bootstrap Opt-ins -->
			<script>
				$(function () {
			  	$('[data-toggle="tooltip"]').tooltip() // Enable Boostrap tooltips
				});
			</script>

			<!-- Only render modals onclick -->
			<script>
	      $('.modal-href').on('click', function() {
	      	$('#modalwizard').modal('toggle');
	      	$("#modalwizard").load("/training/"+this.id+"/?modal=True .modal-dialog");
	      });

	      // Remove contents of modal once it's dismissed to prevent overlap.
	      $('#modalwizard').on('hidden.bs.modal', function (e) {
	      	while (this.hasChildNodes()) {
					    this.removeChild(this.lastChild);
					};
	      });
			</script>

			<!-- Filtering of people -->
			<script>
				$(document).ready(function () { // Filter buttons
					$('.btn-filter').on('click', function() {
					  if (this.id == 'clear') {
					    $('#peopleList > div').removeClass('d-none');
					    $('#peopleList > div.clearfixjs').addClass('clearfix');
					  } 
					  else {
					    var $el = $('.person-' + this.id).removeClass('d-none');
					    $('#peopleList > div').not($el).addClass('d-none');
					    $('#peopleList > div.clearfixjs').removeClass('clearfix');
					  }
					  $('.btn-filter').removeClass('active');
					  $(this).addClass('active');
					})
				});

				$(document).ready(function () {
					var $searchBox = $('#people-search');
					var $userDivs = $('#peopleList > div');

					$searchBox.on('input', function() {
					  var scope = this;
					  if (!scope.value || scope.value == '') {
					    $userDivs.show();
					    $('#peopleList > div.clearfixjs').addClass('clearfix');
					    return;
					  }
					  $userDivs.each(function(i, div) {
					    var $div = $(div);
					    $div.toggle($div.text().toLowerCase().indexOf(scope.value.toLowerCase()) > -1);
					    $('#peopleList > div.clearfixjs').removeClass('clearfix');
					  })
					});
				})

			</script>

			<!-- Card collapse icon toggling -->
			<script>
				$(document).ready(function () { // When we expand a Card, change the icon like magic
				    $("a.collapsea").click(function () {
				        $(this).find(".fa").toggleClass("fa-chevron-down").toggleClass("fa-chevron-up");
				    });
				});
			</script>

			<!-- Expand hidden card rows --> 
			<script>
				$(document).ready(function () { // When expand is clicked, this card's hidden rows are unhidden
				    $(".expandPanel").click(function () {
				    		var dept = $(this).attr('ID') // Get card
				    		var deptClass = dept.replace("expand-",""); // Get dept
				        $(".table-danger."+deptClass).toggleClass("d-none"); // Change class
								$(this).find('#'+deptClass+'-fa').toggleClass("fa-angle-double-down").toggleClass("fa-angle-double-up");
				    });
				});
			</script>

			<!-- Form: Clear input buttons -->
			<script>
				$(document).ready(function () {
					$("#trainingPointsClear").click(function () {
						$('input[id^="id_trainingId_"]:checked').prop('checked',false);
					});
					$("#traineesClear").click(function () {
						$('input[id^="id_trainee_"]:checked').prop('checked',false);
						$(".button-checkbox.active").removeClass("active"); // Remove .active class 
						$(".button-checkbox-icon.fa-check-circle").toggleClass("fa-check-circle").toggleClass("fa-circle");; // Remove .active class 
					});
				});
			</script>
			<!-- Form: Select all for a category -->
			<script>
				$(document).ready(function (){
					var isChecked = false; // Set up for toggling
					$('[id^="selectAll"]').click(function (){ //Get the button
						var dept = $(this).attr('ID');
						var deptCheckboxes = dept.replace("selectAll",".checkbox"); // Change the class prefix
						if (isChecked == false) { // Logic enables toggling, rather than just selecting
							$(deptCheckboxes).prop('checked',true);
							isChecked = true;
						}
						else { 
							$(deptCheckboxes).prop('checked',false);
							isChecked = false;
						}
					});
				});
			</script>
			<!-- Form: Use .active instead of checkbox checked -->
			<script>
				$(document).ready(function () { 
					// Go through and add .active to the initially checked boxes 
					checkboxes = document.getElementsByName("trainee");
					checkedboxes = [];
					for (var i=0; i<checkboxes.length; i++){
						if (checkboxes[i].checked) {
							checkedboxes.push(checkboxes[i]);
							$(checkboxes[i]).closest(".button-checkbox").addClass('active');
							$(checkboxes[i]).closest(".person-checkbox").nextAll(".button-checkbox-icon").addClass("fa-check-circle").removeClass("fa-circle");
						}
					}
				});
			</script>
			<script>
				$('input[name="trainee"]').change(function(){
					// Add .active when the checked status changes 
				    if($(this).is(':checked')) {
				    	// Box gets checked
				      $(this).closest(".button-checkbox").addClass('active');
				      $(this).closest(".person-checkbox").nextAll(".fa-circle").toggleClass("fa-check-circle").toggleClass("fa-circle");
				    } else {
				    	// Unchecked 
				      $(this).closest(".button-checkbox").removeClass('active');
				      $(this).closest(".person-checkbox").nextAll(".fa-check-circle").toggleClass("fa-check-circle").toggleClass("fa-circle");
				    }
				});
			</script>
		<!-- End Javascript -->

	</body>
</html>

nt_training/templates/nt_training/login.html
{% extends 'nt_training/base.html' %}
{% load widget_tweaks %}
{% block title %}Login{% endblock %}

{% block content %}
	{% if user.is_authenticated %}
		<div class="alert alert-warning text-center" role="alert">
			<p><i class="fa fa-fw fa-exclamation-circle"></i> You are already logged in. Try going to the <a href="{% url 'nt_training:ntHome' %}" class="alert-link">home page</a> instead. Or, <a href="{% url 'nt_training:ntLogout' %}" class="alert-link">logout</a>.</p>
			<p>You may have come to this page in error, or because your account does not have the privileges to do whatever it is you just tried.</p>
		</div>
	{% else %}
		<h1 class="text-center">Login</h1>
		{% if form.errors %}
			<div class="row">
				<div class="alert alert-danger col-8 mx-auto" role="alert"><i class="fa fa-exclamation fa-fw"></i> Incorrect username or password. Please try again.</div>
			</div>
		{% endif %}
		{% if next %} 
			{% if "edit" in next or "new" in next %}
				<div class="row">
					<div class="alert alert-warning col-8 mx-auto" role="alert"><i class="fa fa-info fa-fw"></i> You need to log in to do that. Accounts are available to New Theatre technical and workshop committee.</div>
				</div>
			{% endif %}
		{% endif %}
		{# Actual login form #}
		<div class="row">
			<div class="col">
				<form method="post" action="{% url 'nt_training:ntLogin' %}">
					{% csrf_token %}
					{% for field in form %}
						<div class="row form-group">
							<div class="col-lg-8 col-sm-10 col-12 mx-auto">
								<div class="text-left text-primary">{{ field.label_tag|title }}</div>
								{% render_field field class+="form-control" placeholder+=field.label %}
							</div>
						</div>
					{% endfor %}
					<div class="row">
						<div class="col-12 col-sm-10 col-lg-8 mx-auto">
							<button type="submit" value="login" class="btn btn-primary btn-lg btn-block">Login</button>
							<input type="hidden" name="next" value="{{ next }}" />
						</div>
					</div>
				</form>
			</div>
		</div>
	{% endif %}
{% endblock %}

nt_training/templates/nt_training/session-single.html
{% extends 'nt_training/base.html' %}
{% load nt_navbar %}
{% load nt_spec %}
{% block title %}Session {{ object.pk }}{% endblock %}

{% block content %}
	<div class="card">
		<div class="card-header bg-primary">
			<div class="row">
				<div class="col-sm-3 col-12 my-2 my-sm-0 text-center text-sm-left">
			    <a href="{% url 'nt_training:ntSessions' %}" class="btn btn-secondary btn-lg"><i class="fa fa-fw fa-lg fa-list"></i> <span class="d-sm-none d-lg-inline">View all sessions</span></a>
			  </div>
				<div class="col-sm-6 col-12 text-center mt-1">
					<h3 class="">Training Session {{ object.pk }}</h3>
				</div>
				{% if user.is_authenticated %}
				  <div class="col-sm-3 col-12 text-center text-sm-right my-2 my-sm-0">
				    <a href="{% url 'nt_training:ntSessionEdit' object.pk %}" class="btn btn-secondary btn-lg"><i class="fa fa-fw fa-lg fa-edit"></i> <span class="d-sm-none d-lg-inline">Edit</span></a>
				  </div>
				{% endif %}
			</div>
		</div>
		<div class="card-body">
			<div class="row mb-4">
				<div class="col">
					<div class="card">
						<div class="card-header bg-primary">
							<h4><i class="fa fa-fw fa-info nt-orange"></i> Session Info</h4>
						</div>
						<div class="card-body">
							<div class="row text-center text-sm-left">
								<div class="col-12 col-sm-6">
									<h5>Trained by: <a href="{% url 'nt_training:ntPerson' object.trainer.slug %}">{{ object.trainer }}</a></h5>
								</div>
								<div class="col-12 col-sm-6 text-md-right">
									<h5>Date: {{ object.date }}</h5>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="row mb-4">
				<div class="col">
					<div class="card">
						<div class="card-header bg-primary">
							<h4><i class="fa fa-fw fa-list nt-orange"></i> Training Points</h4>
						</div>
						<div class="card-body">
							{% training_cards session_boxes=object.trainingId.all %}
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-12">
					<div class="card">
						<div class="card-header bg-primary">
							<h4><i class="fa fa-fw fa-users nt-orange"></i> People Trained</h4>
						</div>
						<div class="card-body">
								<!-- Need to organise this vertically rather than horizontally -->
								{% with object.trainee.all as people %}
									{% include 'nt_training/include/people-list.html' %}
								{% endwith %}
								
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}